### ISSUE TITLE
Polyline inconsistencies

### ISSUE THREAD

**Issue by jamierobertson1** [sandyre/libopencad#31]
There are inconsistencies between different Polyline implementations, for instance Polyline2d seems only half implemented, (there's a CADPolyline2DObject, but no corresponding CADPolyline2D geometry class). Also the "isClosed" flag is only implemented for LW Polylines. I can submit a pull request if you like and just add a CADPolyline2D class which inherits from CADPolyline3D

Regards

Jamie

**Comment by sandyre** [comment]
Because I haven't found any Polyline2D instances in sample files that I received, I didn't provide a representational class for CADPolyline2D (seems like in latest versions of ACAD polyline2d is completely replaced with lwpolyline, but I am not sure, correct me if I am wrong).

Your PR would be very appreciated.

Alexandr

**Comment by jamierobertson1** [comment]
I've made a PR.

They are still around, although not used so much. If you set 'PLINETYPE' to 0 in AutoCAD, then create a polyline it will be a 2D Polyline rather than a LWPolyline.

Regards

Jamie

**Comment by sandyre** [comment]
Since I have fixed gtests, everything looks good. Thanks for your PR.
